listener 1883 0.0.0.0
listener 2043 0.0.0.0
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/
user mosquitto

#Authentication
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic_security.json