listener 1883 0.0.0.0
listener 2043 0.0.0.0
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/

#Authentication
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_password_init_file /mosquitto/config/admin_pw.txt
plugin_opt_config_file /mosquitto/config/dynamic_security.json