services:
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/frontend/dist
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    command: uvicorn --app-dir backend/src app:app --reload --host 0.0.0.0 --port 8080 --ssl-keyfile ./localhost.key --ssl-certfile ./localhost.crt

  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run start -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secrettest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 2043:2043
    stdin_open: true
    tty: true
    env_file: "./backend/src/.env"
